 const constants = {
  FETCH_TMV2_ALL:"FETCH_TMV2_ALL",
  FETCH_TMV2_DETAIL:"FETCH_TMV2_DETAIL",
  ADD_TMV2:"ADD_TMV2",
  FETCH_TMV3_ALL:"FETCH_TMV3_ALL",
  FETCH_TMV3_DETAIL:"FETCH_TMV3_DETAIL",
  ADD_FILTER_TMV3:"ADD_FILTER_TMV3",
  REMOVE_FILTER_TMV3:"REMOVE_FILTER_TMV3",
  APPLY_TMV3_FILTER:"APPLY_TMV3_FILTER",
  CLEAR_TMV3_FILTER:"CLEAR_TMV3_FILTER",
  FETCH_CIAS_ALL:"FETCH_CIAS_ALL",
  FETCH_CIAS_DETAIL:"FETCH_CIAS_DETAIL",
  FETCH_DTC_ALL:"FETCH_DTC_ALL",
  FETCH_DTC_DETAIL:"FETCH_DTC_DETAIL",
  FETCH_PDCERT_ALL:'FETCH_PDCERT_ALL',
  FETCH_PDCERT_DETAIL:"FETCH_PDCERT_DETAIL",
  ADD_ERROR:'ADD_ERROR',
  CLEAR_ERROR:'CLEAR_ERROR',
  ADD_SAVE_STATUS:"ADD_SAVE_STATUS",
   CLEAR_STATUS:"CLEAR_STATUS",
    CHECKING_LOGIN:"CHECKING_LOGIN",
    LOGIN_SUCCESS:"LOGIN_SUCCESS",
    LOGIN_FAILURE:"LOGIN_FAILURE",
     LOGOUT_USER:"LOGOUT_USER",
     FETCHING:"FETCHING",
     FETCHING_CLEAR:"FETCHING_CLEAR"

};
export default constants;
